# This workflow checks out code, builds an image, performs a container image
# scan, evaluates the image, and promotes it if it passes.

name: Anchore Weekly

on: 
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '38 10 * * 4'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  
        
env:
  ANCHORE_CLI_USER: ${{ secrets.ANCHORE_CLI_USER }}
  ANCHORE_CLI_PASS: ${{ secrets.ANCHORE_CLI_PASS }}
  ANCHORE_CLI_URL: ${{ secrets.ANCHORE_CLI_URL }}
  
jobs:

  Build-Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
    - name: Archive Dockerfile
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: Dockerfile
        retention-days: 2

  Scan-Analyze:
    needs: Build-Push
    runs-on: ubuntu-latest
    steps:
    - name: Download Dockerfile Artifact 
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
    - name: Install anchore-cli
      run: |
        sudo apt-get install python3-pip
        pip install anchorecli
        export PATH="$HOME/.local/bin/:$PATH"
    - name: Verify Anchore Ready and Reachable
      run: |
        anchore-cli system status 
    - name: Add to Enterprise Queue
      run: | 
        anchore-cli image add --noautosubscribe --dockerfile ./Dockerfile ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
        # docker run -e ANCHORE_CLI_USER -e ANCHORE_CLI_PASS -e ANCHORE_CLI_URL --mount type=bind,src=${PWD}/Dockerfile,dst=/Dockerfile anchore/engine-cli anchore-cli image add --noautosubscribe --dockerfile /Dockerfile ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA}
    - name: Wait for Enterprise Analysis
      run: |
        anchore-cli image wait ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}
        # docker run -e ANCHORE_CLI_USER -e ANCHORE_CLI_PASS -e ANCHORE_CLI_URL anchore/engine-cli anchore-cli image wait ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF_NAME}

